# Generated by Django 6.0.3 on 2026-04-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('features', models.JSONField()),
                ('semantic_label', models.CharField(max_length=100)),
                ('aggregation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('File', models.FileField(upload_to='datasets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('semantic_label', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('aggregation', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_bi_app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Summary', models.JSONField()),
                ('Charts', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('File', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_bi_app.file')),
            ],
        ),
    ]
