# Generated by Django 6.0.3 on 2026-04-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_bi_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='File',
        ),
        migrations.RemoveField(
            model_name='columnprediction',
            name='file',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Charts',
            new_name='charts',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='datasets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='columnprediction',
            name='dataset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mini_bi_app.dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='dataset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mini_bi_app.dataset'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
