# Generated by Django 6.0.3 on 2026-04-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_bi_app', '0002_remove_report_file_remove_columnprediction_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
    ]
