# Generated by Django 6.0.3 on 2026-05-02 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_bi_app', '0003_remove_report_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columntrainingdata',
            name='aggregation',
        ),
        migrations.AddField(
            model_name='columntrainingdata',
            name='sample_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
